management:
  security:
    enabled: false
       
security:
  sessions: NEVER
  oauth2:
    resource:
      userInfoUri: http://10.0.4.33:8080/auth/realms/mykeycloak/protocol/openid-connect/userinfo
# Configure resources  
secEnabled: false
auth:
   - api: /entities
     role: 
      - USER_PG
      - USER_PUG
      - ADMIN_PUGD
     method:
       POST
   - api: /entities
     role: 
      - USER_G
      - USER_PG
      - USER_PUG
      - USER_GUD
      - ADMIN_PUGD
     method:
       GET
   - api: /entities/*
     role: 
      - USER_G
      - USER_PG
      - USER_PUG
      - USER_GUD
     method:
       GET
   - api: /entities/*
     role: 
      - USER_GUD
      - ADMIN_PUGD
     method:
       DELETE  
   - api: /entities/*/attrs/
     role: 
      - USER_PG
      - USER_PUG
      - ADMIN_PUGD
     method:
       POST
   - api: /entities/*/attrs/*
     role: 
      - USER_GUD
      - ADMIN_PUGD
     method:
       DELETE
   - api: /entities/*/attrs/*/*
     role: 
      - USER_GUD
      - USER_PUG
      - ADMIN_PUGD
     method:
       PATCH
   - api: /entities/*/attrs/*/*
     role: 
      - USER_GUD
      - ADMIN_PUGD
     method:
       DELETE