version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181"
    logging:
      driver: none
  kafka:
    image: bitnami/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    logging:
      driver: none
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    logging:
      driver: none
  emgr:
    image: scorpiobroker/scorpio:EntityManager_latest
    ports:
      - "1025"
    depends_on:
      - kafka
      - eureka
  eureka:
    image: scorpiobroker/scorpio:eureka-server_latest
    ports:
      - "8761"
  gateway:
    image: scorpiobroker/scorpio:gateway_latest
    ports:
      - "9090:9090"
    depends_on:
      - eureka
  histmgr:
    image: scorpiobroker/scorpio:HistoryManager_latest
    ports:
      - "1040"
    depends_on:
      - kafka
      - gateway
      - eureka
  qrymgr:
    image: scorpiobroker/scorpio:QueryManager_latest
    ports:
      - "1026"
    depends_on:
      - kafka
      - postgres
      - eureka
  regmgr:
    image: scorpiobroker/scorpio:RegistryManager_latest
    ports:
      - "1030"
    depends_on:
      - kafka
      - postgres
      - gateway
      - eureka
  regsbsmgr:
    image: scorpiobroker/scorpio:RegistrySubscriptionManager_latest
    ports:
      - "2025"
    depends_on:
      - kafka
      - postgres
      - eureka
  sbsmgr:
    image: scorpiobroker/scorpio:SubscriptionManager_latest
    ports:
      - "2026"
    depends_on:
      - kafka
      - eureka
