
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


#GET request configuration for QUERY-MANAGER 
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
server:
  port: 9090
  tomcat:
    max:
      threads:2000



eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Configure the Authorization Server and User Info Resource Server details
security:
  active: false
  oauth2:
    client:
    # for keycloak configure
      #accessTokenUri: http://10.0.4.33:8080/auth/realms/mykeycloak/protocol/openid-connect/token
      #userAuthorizationUri: http://10.0.4.33:8080/auth/realms/mykeycloak/protocol/openid-connect/auth
      #clientId: authserver
      #clientSecret: ae8c99a9-f98d-41e9-8fb2-d348acb987e0
    # for ketrock configure  
      accessTokenUri: http://172.30.64.120:3000/oauth2/token
      userAuthorizationUri: http://172.30.64.120:3000/oauth2/authorize
      clientId: a2034c11-d2a9-4cab-9fac-ff65425bd53f
      clientSecret: 7364baec-6d6f-4307-8c71-d66e1e6c3afc
    resource:
    # for keycloak configure
      #userInfoUri: http://10.0.4.33:8080/auth/realms/mykeycloak/protocol/openid-connect/userinfo
    # for keycloak configure
      userInfoUri: http://172.30.64.120:3000/user

spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      routes:
      - id: websocket_route
        uri: lb:ws://SUBSCRIPTION-MANAGER
        predicates:
        - Path=/websocket/**