mysettings:
  eureka:
    protocol: ${eurekaprotocol:http}
    host: ${eurekahost:localhost}
    port: ${eurekaport:8761}
eurekaurl: ${mysettings.eureka.protocol}://${mysettings.eureka.host}:${mysettings.eureka.port}
spring:
  profiles:
    active: native
  application:
    name: configserver
  main:
    lazy-initialization: true
  cloud:
    config:
      server:
        bootstrap: true
        native:
          searchLocations: classpath:/config
          
eureka:
  client:
    serviceUrl:
      defaultZone: ${eurekaurl}/eureka/
    registerWithEureka: true
    fetchRegistry: true
server:
  port: 8888
logging:
  level:
    root: ERROR
#spring.cloud.config.server.git.uri=https://github.com/husseinterek/spring-cloud-repo.git
